### ISSUE TITLE
Error when upgrading to 2.1.1.

### ISSUE THREAD

**Issue by RichardEyres** [zpqrtbnk/Zbu.ModelsBuilder#44] opened 2015-03-18 11:20 UTC
Hello

I originally posted this on the Umbraco Forums (https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/63255-Error-using-ZbuModelsBuilder-211).

Upgraded to 2.1.1. (installed a fresh install on my VS2013 machine - needed to be rebuilt, and upgraded the package on my dev site).
Ran the external program as per the instructions - and the follow occurs.

Any ideas?

ZbuModelsBuilder: ZbuModelsBuilder failed to generate code: Exception: Response status code does not indicate success (InternalServerError)

{"Message":"An error has occurred.","ExceptionMessage":"Common Language Runtime detected an invalid program.","ExceptionType":"System.InvalidProgramException","StackTrace":"   at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)\r\n   at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.PushLeft(SortedInt32KeyNode`1 node)\r\n   at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator..ctor(SortedInt32KeyNode`1 root)\r\n   at System.Collections.Immutable.ImmutableDictionary`2.Enumerator..ctor(SortedInt32KeyNode`1 root, Builder builder)\r\n   at System.Collections.Immutable.ImmutableDictionary`2.GetEnumerator()\r\n   at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 arrayIndex)\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)\r\n   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<>c__DisplayClass0.<_ctor>b__1()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<_ctor>b__4()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.GetMergedReferenceDirectives()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.get_ReferenceDirectives()\r\n   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)\r\n   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.get_SourceAssembly()\r\n   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredNamespace(NamespaceDeclarationSyntax declarationSyntax)\r\n   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredNamespaceOrType(CSharpSyntaxNode declarationSyntax)\r\n   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredTypeMemberContainer(CSharpSyntaxNode memberDeclaration)\r\n   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(BaseTypeDeclarationSyntax declarationSyntax, CancellationToken cancellationToken)\r\n   at Zbu.ModelsBuilder.Building.CodeParser.<>c__DisplayClass8.<Parse>b__0(ClassDeclarationSyntax x)\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at Zbu.ModelsBuilder.Building.CodeParser.Parse(ParseResult disco, CSharpCompilation compilation, SyntaxTree tree)\r\n   at Zbu.ModelsBuilder.Building.CodeParser.Parse(IDictionary`2 files, IEnumerable`1 referencedAssemblies)\r\n   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApiController.GetModels(GetModelsData data)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)"}

ZbuModelsBuilder:    at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.EnsureSuccess(HttpResponseMessage result)

   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.GetModels(Dictionary`2 ourFiles, String modelsNamespace)

   at Zbu.ModelsBuilder.CustomTool.CustomTool.ZbuModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)

**Comment by zpqrtbnk** [comment] 2015-03-18 12:06
Interesting. Somewhere while parsing the code that you have in the builder's directory, Roslyn crashes. Is there any way you can share that code (ie any *.cs file living in the same directory as the file that has the custom tool configured)? Either publicly or via email? In addition, do you have any "special" or additional assemblies added to your umbraco's ~/bin folder?

**Comment by zpqrtbnk** [comment] 2015-03-18 12:15
Might be related to Roslyn issue https://github.com/dotnet/roslyn/issues/968 - which is scheduled to be fixed in 1.0-rc2. Looking into it.

**Comment by RichardEyres** [comment] 2015-03-18 12:20
I am about to go into a meeting, so will send you the code once i am out.
however, this is the general lowdown.

The models builder is in a Library. There is a Models folder, that has the builder class (empty), an EDMX of the database, and partial classes to extend the models built by the builder. There is also a number of sub folders containing self contained models.

The site/library uses ArcheType, Automapper, NuPickers. Will get a list constructed and sent over to you.

Thank you for your time looking at this issue.

**Comment by RichardEyres** [comment] 2015-03-18 15:09
I have added the models (and bin dir) in this dropbox location. Hope this helps:

https://dl.dropboxusercontent.com/u/9709374/Models.zip

**Comment by zpqrtbnk** [comment] 2015-03-18 15:20
If (if) it is caused by the Roslyn bug, which in turns is related to an Immutable library bug, caused by a JIT bug, then it will be fixed with the next version of Roslyn, but in the meantime it seems that the JIT bug has been fixed in .NET 4.5.2. What version are you running?

I have downloaded your files and will try to repro later today.

**Comment by RichardEyres** [comment] 2015-03-18 15:33
It has been built against 4.5.1

**Comment by zpqrtbnk** [comment] 2015-03-18 15:34
Any chance you can try 4.5.2?

**Comment by RichardEyres** [comment] 2015-03-18 17:01
I installed 4.5.2 and rebooted.
I did not change the version within VS and decided to just give it a quick try before i changed it to 4.5.2. 

It worked without an issue and I got the generated class i was expecting.

I take it that the models builder requires 4.5.2 on the machine before it works?

Regardless, thank you for the assistance and great software.

If you post in the Umbraco Forum, i will mark you as the solution for the Karma.

**Comment by zpqrtbnk** [comment] 2015-03-18 17:26
Well, until they release Roslyn 1.0-rc2, the models builder will require 4.5.2 ;-(

**Comment by zpqrtbnk** [comment] 2015-05-03 08:52
Roslyn 1.0-rc2 is out! Adding upgrade to next milestone.

**Comment by zpqrtbnk** [comment] 2015-05-03 14:23
Should be fixed with 2.1.2.

**Closed by zpqrtbnk** 2015-05-03 14:23 UTC
Labels: bug
