### ISSUE TITLE
API version conflict: client version (8.0.2) is not compatible with server version(3.0.10.102)

### ISSUE THREAD

**Issue by rosswebediaglasgow** [zpqrtbnk/Zbu.ModelsBuilder#193] opened 2019-03-07 14:25 UTC
When running custom tool, it fails and I receive this error in output:

API version conflict: client version (8.0.2) is not compatible with server version(3.0.10.102)

**Comment by zpqrtbnk** [comment] 2019-03-07 14:45
Duplicate of #190

**Closed by zpqrtbnk** 2019-03-07 14:45 UTC
Labels: type/bug
