### ISSUE TITLE
Nested content composition generate errors

### ISSUE THREAD

**Issue by vonbarnekowa** [zpqrtbnk/Zbu.ModelsBuilder#188] opened 2019-02-28 12:36 UTC
When you have a document type that have the "Is an Element type" checkbox checked and inherits from a composition that doesn't have that ticked, the child will inherit from a wrong class that will generate errors during the build.

Umbraco version: 8.0.0
Modelsbuilder version: 8.0.1

**Comment by zpqrtbnk** [comment] 2019-03-05 11:04
Reproduced.

We generate:
```
public partial interface ICompose : IPublishedContent { ... }

public partial class Compose : PublishedContentModel, ICompose { ... }

public partial class Composed : PublishedElementModel, ICompose { ... }
```

And get error
```
Failed to build Live models.
'Composed' does not implement interface member 'IPublishedContent.GetUrl(string)'
```

Because `Composed` is a published *element* but implements `ICompose` which is a published *content*.

**Comment by zpqrtbnk** [comment] 2019-03-05 11:13
Several things to consider here.

It works if `Compose` is also an element. Being an element does *not* prevent it from being used by a composed *content* - but if the content is accessed via the `ICompose` interface, then only the composition properties are accessible (no children, parent, url...). But that's a limitation, not an error.

Should Core makes sure that an element can only be composed of elements? Maybe - but then, switching between element and content would need to trigger checks to ensure that the change is legit.

At Models Builder level, there's no way we can support an element being composed of a content.

So... at Models Builder level, I think I could detect the situation and raise a much nicer error (eg "*cannot generate models because type Composed is an element but is composed of Compose which is a content*").

This, and create a task for Core to try to prevent the situation entirely, eventually.

What do you think?

**Comment by zpqrtbnk** [comment] 2019-03-05 11:49
I have improved the error message as explained above, and it will be part of the next MB version.

I have created [this Core issue](https://github.com/umbraco/Umbraco-CMS/issues/4863) so that we eventually ensure that Core does not allow this situation to happen.

Thoughts?

**Comment by zpqrtbnk** [comment] 2019-03-06 09:13
Improved error message is going to be part of Models Builder 8.0.2, done in source, see core task [4880](https://github.com/umbraco/Umbraco-CMS/issues/4880) for release.

**Comment by zpqrtbnk** [comment] 2019-04-02 17:11
merged fixed

**Closed by zpqrtbnk** 2019-04-02 17:11 UTC
Labels: state/pending-core, type/bug
