### ISSUE TITLE
Easier way to cast members to ModelsBuilder model

### ISSUE THREAD

**Issue by bjarnef** [zpqrtbnk/Zbu.ModelsBuilder#187] opened 2019-02-27 14:36 UTC
When you want to get multiple members in Umbraco, `MemberShipHelper` is a bit limited and doesn't offer same methods as in `MemberService`, e.g. when you want to get a collection of members by member type, where MemberService offer the method `GetMembersByMemberType` which return `IEnumerable<IMember>`.
I have a member type called `clickAndCollect`, but it isn't straightforward to cast this to `IEnumerable<ClickAndCollect>`.

I tried some different approaches as these:

```
var ms = ApplicationContext.Current.Services.MemberService;

var membersByType = ms.GetMembersByMemberType(ContentModels.ClickAndCollect.ModelTypeAlias);

// Works
var test1 = membersByType.Select(x => new MemberPublishedContent(x));
var count1 = test1.Count();

// Doesn't work
var test2 = membersByType.OfType<MemberPublishedContent>();
var count2 = test2.Count();

// Doesn't work
var click1 = test1.OfType<ContentModels.ClickAndCollect>();
var count3 = click1.Count();

// Works
var click2 = test1.OfType<IPublishedContent>();
var count4 = click2.Count();

// Doesn't work
var click3 = click2.OfType<ContentModels.ClickAndCollect>();
var count5 = click3.Count();

// Works
var click4 = click2.Select(x => new ContentModels.ClickAndCollect(x));
var count6 = click4.Count();
```

It would be great if `MemberShipHelper` had some of these methods, e.g. `GetMembersByMemberType` (could be a paged collection) which returned `IEnumerable<IPublishedContent>` and you can then cast this to this model using `.OfType<ClickAndCollect>()`

Furthermore it would be great if ModelsBuilder also generate the `Email` property as is available on both `IMember` and `MemberPublishedContent`. This specific issue is reported here: https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/148

**Comment by bjarnef** [comment] 2019-02-27 19:22
This also seems to work.

```
var ms = ApplicationContext.Current.Services.MemberService;

var members = ms.GetMembersByMemberType(ContentModels.ClickAndCollect.ModelTypeAlias);

var temp1 = members.Select(m => new MemberPublishedContent(m));
var temp2 = temp1.Select(m => new ContentModels.ClickAndCollect(m));
```

**Comment by zpqrtbnk** [comment] 2019-03-04 08:39
You are trying to use models with services... and they have not been designed to work together.

What you get from `MembershipHelper` is models, which are already `MemberPublishedContent`. What you get from `MemberService` is `IMember` instances, and then you need to explicitly create a `MemberPublishedContent`, as you have discovered. And then, the `temp1`/`temp2` steps you describe above are indeed the way to go.

There is little we can do at Models Builder here.

But ultimately, if I understand correctly, the root of the problem is that `MembershipHelper` does not allow you to get members of a given type? So, we'd need a feature request for Core, so we can do (with paging support):

```
var members = Umbraco.MembersOfType(0, 100, out var total, "someTypeAlias");
```

Making sense?

**Comment by bjarnef** [comment] 2019-03-04 09:11
@zpqrtbnk I know, but unfortunately `UmbracoHelper` or `MembershipHelper` in v7 didn't expose any methods to fetch multiple members e.g. by id, member type etc.

I can fetch members by type from `MemberService`.

```
var ms = ApplicationContext.Current.Services.MemberService;
var members = ms.GetMembersByMemberType(ContentModels.ClickAndCollect.ModelTypeAlias);
```

and then select e.g. select ids an an array, loop these to lookup each member using `Umbraco.TypedMember(int id)`.

But it seems doubled since I already have a collection of `IMember`. The `MemberOfType` was added in v8.

I guess there is no easy way to do this in v7. In this case it is creating an Examine index using a members of a specific type and adding some additional properties with some external data.

**Comment by zpqrtbnk** [comment] 2019-03-04 09:27
I am afraid there is no easy way in v7, and none will be implemented indeed.

As for v8... `MembersOfType` does not exist yet, so maybe it's worth creating a feature request. Done it, see [issue 4835](https://github.com/umbraco/Umbraco-CMS/issues/4835).

And, closing this issue, if that's OK with you.

**Closed by zpqrtbnk** 2019-03-04 09:27 UTC

**Comment by bjarnef** [comment] 2019-03-04 09:38
Thanks @zpqrtbnk and great to see these improvements in v8.
