### ISSUE TITLE
Model name suffix

### ISSUE THREAD

**Issue by mmadukah** [zpqrtbnk/Zbu.ModelsBuilder#217] opened 2019-09-05 09:20 UTC
Is there any chance of adding functionality to add a suffix to the generated models as the generated names tend to clash with our POCO domain model names?

**Comment by mmadukah** [comment] 2019-09-05 09:23
# #213

**Comment by zpqrtbnk** [comment] 2019-09-05 09:24
Yes, and directly related to #213 which is about prefix. Adding to backlog too.

**Comment by zpqrtbnk** [comment] 2019-09-05 10:02
Closing as duplicate of #213 which is in-progress.

**Closed as completed by zpqrtbnk** 2019-09-05 10:02 UTC
Labels: type/feature
